/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.msroute.client.model.FloorDTO;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SeatDTO
 */
@JsonPropertyOrder({
  SeatDTO.JSON_PROPERTY_ID,
  SeatDTO.JSON_PROPERTY_SEAT_NO,
  SeatDTO.JSON_PROPERTY_ROW,
  SeatDTO.JSON_PROPERTY_COL,
  SeatDTO.JSON_PROPERTY_PRICE_FACTOR,
  SeatDTO.JSON_PROPERTY_CREATED_AT,
  SeatDTO.JSON_PROPERTY_UPDATED_AT,
  SeatDTO.JSON_PROPERTY_IS_DELETED,
  SeatDTO.JSON_PROPERTY_DELETED_AT,
  SeatDTO.JSON_PROPERTY_DELETED_BY,
  SeatDTO.JSON_PROPERTY_FLOOR
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class SeatDTO {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_SEAT_NO = "seatNo";
  @jakarta.annotation.Nonnull
  private String seatNo;

  public static final String JSON_PROPERTY_ROW = "row";
  @jakarta.annotation.Nullable
  private Integer row;

  public static final String JSON_PROPERTY_COL = "col";
  @jakarta.annotation.Nullable
  private Integer col;

  public static final String JSON_PROPERTY_PRICE_FACTOR = "priceFactor";
  @jakarta.annotation.Nullable
  private BigDecimal priceFactor;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public static final String JSON_PROPERTY_FLOOR = "floor";
  @jakarta.annotation.Nonnull
  private FloorDTO floor;

  public SeatDTO() {
  }

  public SeatDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public SeatDTO seatNo(@jakarta.annotation.Nonnull String seatNo) {
    
    this.seatNo = seatNo;
    return this;
  }

  /**
   * Get seatNo
   * @return seatNo
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SEAT_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSeatNo() {
    return seatNo;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSeatNo(@jakarta.annotation.Nonnull String seatNo) {
    this.seatNo = seatNo;
  }


  public SeatDTO row(@jakarta.annotation.Nullable Integer row) {
    
    this.row = row;
    return this;
  }

  /**
   * Get row
   * @return row
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRow() {
    return row;
  }


  @JsonProperty(JSON_PROPERTY_ROW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRow(@jakarta.annotation.Nullable Integer row) {
    this.row = row;
  }


  public SeatDTO col(@jakarta.annotation.Nullable Integer col) {
    
    this.col = col;
    return this;
  }

  /**
   * Get col
   * @return col
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCol() {
    return col;
  }


  @JsonProperty(JSON_PROPERTY_COL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCol(@jakarta.annotation.Nullable Integer col) {
    this.col = col;
  }


  public SeatDTO priceFactor(@jakarta.annotation.Nullable BigDecimal priceFactor) {
    
    this.priceFactor = priceFactor;
    return this;
  }

  /**
   * Get priceFactor
   * @return priceFactor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPriceFactor() {
    return priceFactor;
  }


  @JsonProperty(JSON_PROPERTY_PRICE_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPriceFactor(@jakarta.annotation.Nullable BigDecimal priceFactor) {
    this.priceFactor = priceFactor;
  }


  public SeatDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public SeatDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public SeatDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public SeatDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public SeatDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  public SeatDTO floor(@jakarta.annotation.Nonnull FloorDTO floor) {
    
    this.floor = floor;
    return this;
  }

  /**
   * Get floor
   * @return floor
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FLOOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FloorDTO getFloor() {
    return floor;
  }


  @JsonProperty(JSON_PROPERTY_FLOOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFloor(@jakarta.annotation.Nonnull FloorDTO floor) {
    this.floor = floor;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SeatDTO seatDTO = (SeatDTO) o;
    return Objects.equals(this.id, seatDTO.id) &&
        Objects.equals(this.seatNo, seatDTO.seatNo) &&
        Objects.equals(this.row, seatDTO.row) &&
        Objects.equals(this.col, seatDTO.col) &&
        Objects.equals(this.priceFactor, seatDTO.priceFactor) &&
        Objects.equals(this.createdAt, seatDTO.createdAt) &&
        Objects.equals(this.updatedAt, seatDTO.updatedAt) &&
        Objects.equals(this.isDeleted, seatDTO.isDeleted) &&
        Objects.equals(this.deletedAt, seatDTO.deletedAt) &&
        Objects.equals(this.deletedBy, seatDTO.deletedBy) &&
        Objects.equals(this.floor, seatDTO.floor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, seatNo, row, col, priceFactor, createdAt, updatedAt, isDeleted, deletedAt, deletedBy, floor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SeatDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    seatNo: ").append(toIndentedString(seatNo)).append("\n");
    sb.append("    row: ").append(toIndentedString(row)).append("\n");
    sb.append("    col: ").append(toIndentedString(col)).append("\n");
    sb.append("    priceFactor: ").append(toIndentedString(priceFactor)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("    floor: ").append(toIndentedString(floor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

