/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.msroute.client.model.TripDTO;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TripSeatDTO
 */
@JsonPropertyOrder({
  TripSeatDTO.JSON_PROPERTY_ID,
  TripSeatDTO.JSON_PROPERTY_SEAT_NO,
  TripSeatDTO.JSON_PROPERTY_FLOOR_NO,
  TripSeatDTO.JSON_PROPERTY_BOOKED,
  TripSeatDTO.JSON_PROPERTY_PRICE_FACTOR,
  TripSeatDTO.JSON_PROPERTY_CREATED_AT,
  TripSeatDTO.JSON_PROPERTY_UPDATED_AT,
  TripSeatDTO.JSON_PROPERTY_IS_DELETED,
  TripSeatDTO.JSON_PROPERTY_DELETED_AT,
  TripSeatDTO.JSON_PROPERTY_DELETED_BY,
  TripSeatDTO.JSON_PROPERTY_TRIP
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class TripSeatDTO {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_SEAT_NO = "seatNo";
  @jakarta.annotation.Nonnull
  private String seatNo;

  public static final String JSON_PROPERTY_FLOOR_NO = "floorNo";
  @jakarta.annotation.Nonnull
  private Integer floorNo;

  public static final String JSON_PROPERTY_BOOKED = "booked";
  @jakarta.annotation.Nullable
  private Boolean booked;

  public static final String JSON_PROPERTY_PRICE_FACTOR = "priceFactor";
  @jakarta.annotation.Nullable
  private BigDecimal priceFactor;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public static final String JSON_PROPERTY_TRIP = "trip";
  @jakarta.annotation.Nonnull
  private TripDTO trip;

  public TripSeatDTO() {
  }

  public TripSeatDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public TripSeatDTO seatNo(@jakarta.annotation.Nonnull String seatNo) {
    
    this.seatNo = seatNo;
    return this;
  }

  /**
   * Get seatNo
   * @return seatNo
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SEAT_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSeatNo() {
    return seatNo;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSeatNo(@jakarta.annotation.Nonnull String seatNo) {
    this.seatNo = seatNo;
  }


  public TripSeatDTO floorNo(@jakarta.annotation.Nonnull Integer floorNo) {
    
    this.floorNo = floorNo;
    return this;
  }

  /**
   * Get floorNo
   * @return floorNo
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FLOOR_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getFloorNo() {
    return floorNo;
  }


  @JsonProperty(JSON_PROPERTY_FLOOR_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFloorNo(@jakarta.annotation.Nonnull Integer floorNo) {
    this.floorNo = floorNo;
  }


  public TripSeatDTO booked(@jakarta.annotation.Nullable Boolean booked) {
    
    this.booked = booked;
    return this;
  }

  /**
   * Get booked
   * @return booked
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BOOKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getBooked() {
    return booked;
  }


  @JsonProperty(JSON_PROPERTY_BOOKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBooked(@jakarta.annotation.Nullable Boolean booked) {
    this.booked = booked;
  }


  public TripSeatDTO priceFactor(@jakarta.annotation.Nullable BigDecimal priceFactor) {
    
    this.priceFactor = priceFactor;
    return this;
  }

  /**
   * Get priceFactor
   * @return priceFactor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPriceFactor() {
    return priceFactor;
  }


  @JsonProperty(JSON_PROPERTY_PRICE_FACTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPriceFactor(@jakarta.annotation.Nullable BigDecimal priceFactor) {
    this.priceFactor = priceFactor;
  }


  public TripSeatDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public TripSeatDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public TripSeatDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public TripSeatDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public TripSeatDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  public TripSeatDTO trip(@jakarta.annotation.Nonnull TripDTO trip) {
    
    this.trip = trip;
    return this;
  }

  /**
   * Get trip
   * @return trip
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRIP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TripDTO getTrip() {
    return trip;
  }


  @JsonProperty(JSON_PROPERTY_TRIP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTrip(@jakarta.annotation.Nonnull TripDTO trip) {
    this.trip = trip;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TripSeatDTO tripSeatDTO = (TripSeatDTO) o;
    return Objects.equals(this.id, tripSeatDTO.id) &&
        Objects.equals(this.seatNo, tripSeatDTO.seatNo) &&
        Objects.equals(this.floorNo, tripSeatDTO.floorNo) &&
        Objects.equals(this.booked, tripSeatDTO.booked) &&
        Objects.equals(this.priceFactor, tripSeatDTO.priceFactor) &&
        Objects.equals(this.createdAt, tripSeatDTO.createdAt) &&
        Objects.equals(this.updatedAt, tripSeatDTO.updatedAt) &&
        Objects.equals(this.isDeleted, tripSeatDTO.isDeleted) &&
        Objects.equals(this.deletedAt, tripSeatDTO.deletedAt) &&
        Objects.equals(this.deletedBy, tripSeatDTO.deletedBy) &&
        Objects.equals(this.trip, tripSeatDTO.trip);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, seatNo, floorNo, booked, priceFactor, createdAt, updatedAt, isDeleted, deletedAt, deletedBy, trip);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TripSeatDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    seatNo: ").append(toIndentedString(seatNo)).append("\n");
    sb.append("    floorNo: ").append(toIndentedString(floorNo)).append("\n");
    sb.append("    booked: ").append(toIndentedString(booked)).append("\n");
    sb.append("    priceFactor: ").append(toIndentedString(priceFactor)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("    trip: ").append(toIndentedString(trip)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

