/*
 * Ms Promotion API
 * Ms Promotion API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.mspromotion.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.mspromotion.client.model.PromotionDTO;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConditionByDateDTO
 */
@JsonPropertyOrder({
  ConditionByDateDTO.JSON_PROPERTY_ID,
  ConditionByDateDTO.JSON_PROPERTY_SPECIFIC_DATE,
  ConditionByDateDTO.JSON_PROPERTY_WEEKDAY,
  ConditionByDateDTO.JSON_PROPERTY_CREATED_AT,
  ConditionByDateDTO.JSON_PROPERTY_UPDATED_AT,
  ConditionByDateDTO.JSON_PROPERTY_IS_DELETED,
  ConditionByDateDTO.JSON_PROPERTY_DELETED_AT,
  ConditionByDateDTO.JSON_PROPERTY_DELETED_BY,
  ConditionByDateDTO.JSON_PROPERTY_PROMOTION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class ConditionByDateDTO {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_SPECIFIC_DATE = "specificDate";
  @jakarta.annotation.Nullable
  private LocalDate specificDate;

  public static final String JSON_PROPERTY_WEEKDAY = "weekday";
  @jakarta.annotation.Nullable
  private Integer weekday;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public static final String JSON_PROPERTY_PROMOTION = "promotion";
  @jakarta.annotation.Nonnull
  private PromotionDTO promotion;

  public ConditionByDateDTO() {
  }

  public ConditionByDateDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public ConditionByDateDTO specificDate(@jakarta.annotation.Nullable LocalDate specificDate) {
    
    this.specificDate = specificDate;
    return this;
  }

  /**
   * Get specificDate
   * @return specificDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SPECIFIC_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getSpecificDate() {
    return specificDate;
  }


  @JsonProperty(JSON_PROPERTY_SPECIFIC_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpecificDate(@jakarta.annotation.Nullable LocalDate specificDate) {
    this.specificDate = specificDate;
  }


  public ConditionByDateDTO weekday(@jakarta.annotation.Nullable Integer weekday) {
    
    this.weekday = weekday;
    return this;
  }

  /**
   * Get weekday
   * @return weekday
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEEKDAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWeekday() {
    return weekday;
  }


  @JsonProperty(JSON_PROPERTY_WEEKDAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeekday(@jakarta.annotation.Nullable Integer weekday) {
    this.weekday = weekday;
  }


  public ConditionByDateDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public ConditionByDateDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public ConditionByDateDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public ConditionByDateDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public ConditionByDateDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  public ConditionByDateDTO promotion(@jakarta.annotation.Nonnull PromotionDTO promotion) {
    
    this.promotion = promotion;
    return this;
  }

  /**
   * Get promotion
   * @return promotion
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROMOTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PromotionDTO getPromotion() {
    return promotion;
  }


  @JsonProperty(JSON_PROPERTY_PROMOTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPromotion(@jakarta.annotation.Nonnull PromotionDTO promotion) {
    this.promotion = promotion;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConditionByDateDTO conditionByDateDTO = (ConditionByDateDTO) o;
    return Objects.equals(this.id, conditionByDateDTO.id) &&
        Objects.equals(this.specificDate, conditionByDateDTO.specificDate) &&
        Objects.equals(this.weekday, conditionByDateDTO.weekday) &&
        Objects.equals(this.createdAt, conditionByDateDTO.createdAt) &&
        Objects.equals(this.updatedAt, conditionByDateDTO.updatedAt) &&
        Objects.equals(this.isDeleted, conditionByDateDTO.isDeleted) &&
        Objects.equals(this.deletedAt, conditionByDateDTO.deletedAt) &&
        Objects.equals(this.deletedBy, conditionByDateDTO.deletedBy) &&
        Objects.equals(this.promotion, conditionByDateDTO.promotion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, specificDate, weekday, createdAt, updatedAt, isDeleted, deletedAt, deletedBy, promotion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConditionByDateDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    specificDate: ").append(toIndentedString(specificDate)).append("\n");
    sb.append("    weekday: ").append(toIndentedString(weekday)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("    promotion: ").append(toIndentedString(promotion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

