/*
 * Ms User API
 * Ms User API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.msuser.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UserPreferencesDTO
 */
@JsonPropertyOrder({
  UserPreferencesDTO.JSON_PROPERTY_ID,
  UserPreferencesDTO.JSON_PROPERTY_PREFERRED_LANGUAGE,
  UserPreferencesDTO.JSON_PROPERTY_EMAIL_NOTIFICATIONS,
  UserPreferencesDTO.JSON_PROPERTY_SMS_NOTIFICATIONS,
  UserPreferencesDTO.JSON_PROPERTY_PUSH_NOTIFICATIONS,
  UserPreferencesDTO.JSON_PROPERTY_PHONE,
  UserPreferencesDTO.JSON_PROPERTY_EMAIL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class UserPreferencesDTO {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_PREFERRED_LANGUAGE = "preferredLanguage";
  @jakarta.annotation.Nullable
  private String preferredLanguage;

  public static final String JSON_PROPERTY_EMAIL_NOTIFICATIONS = "emailNotifications";
  @jakarta.annotation.Nullable
  private Boolean emailNotifications;

  public static final String JSON_PROPERTY_SMS_NOTIFICATIONS = "smsNotifications";
  @jakarta.annotation.Nullable
  private Boolean smsNotifications;

  public static final String JSON_PROPERTY_PUSH_NOTIFICATIONS = "pushNotifications";
  @jakarta.annotation.Nullable
  private Boolean pushNotifications;

  public static final String JSON_PROPERTY_PHONE = "phone";
  @jakarta.annotation.Nullable
  private String phone;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @jakarta.annotation.Nullable
  private String email;

  public UserPreferencesDTO() {
  }

  public UserPreferencesDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public UserPreferencesDTO preferredLanguage(@jakarta.annotation.Nullable String preferredLanguage) {
    
    this.preferredLanguage = preferredLanguage;
    return this;
  }

  /**
   * Get preferredLanguage
   * @return preferredLanguage
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREFERRED_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPreferredLanguage() {
    return preferredLanguage;
  }


  @JsonProperty(JSON_PROPERTY_PREFERRED_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreferredLanguage(@jakarta.annotation.Nullable String preferredLanguage) {
    this.preferredLanguage = preferredLanguage;
  }


  public UserPreferencesDTO emailNotifications(@jakarta.annotation.Nullable Boolean emailNotifications) {
    
    this.emailNotifications = emailNotifications;
    return this;
  }

  /**
   * Get emailNotifications
   * @return emailNotifications
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL_NOTIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEmailNotifications() {
    return emailNotifications;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL_NOTIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmailNotifications(@jakarta.annotation.Nullable Boolean emailNotifications) {
    this.emailNotifications = emailNotifications;
  }


  public UserPreferencesDTO smsNotifications(@jakarta.annotation.Nullable Boolean smsNotifications) {
    
    this.smsNotifications = smsNotifications;
    return this;
  }

  /**
   * Get smsNotifications
   * @return smsNotifications
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SMS_NOTIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSmsNotifications() {
    return smsNotifications;
  }


  @JsonProperty(JSON_PROPERTY_SMS_NOTIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSmsNotifications(@jakarta.annotation.Nullable Boolean smsNotifications) {
    this.smsNotifications = smsNotifications;
  }


  public UserPreferencesDTO pushNotifications(@jakarta.annotation.Nullable Boolean pushNotifications) {
    
    this.pushNotifications = pushNotifications;
    return this;
  }

  /**
   * Get pushNotifications
   * @return pushNotifications
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUSH_NOTIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPushNotifications() {
    return pushNotifications;
  }


  @JsonProperty(JSON_PROPERTY_PUSH_NOTIFICATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPushNotifications(@jakarta.annotation.Nullable Boolean pushNotifications) {
    this.pushNotifications = pushNotifications;
  }


  public UserPreferencesDTO phone(@jakarta.annotation.Nullable String phone) {
    
    this.phone = phone;
    return this;
  }

  /**
   * Get phone
   * @return phone
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhone() {
    return phone;
  }


  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhone(@jakarta.annotation.Nullable String phone) {
    this.phone = phone;
  }


  public UserPreferencesDTO email(@jakarta.annotation.Nullable String email) {
    
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(@jakarta.annotation.Nullable String email) {
    this.email = email;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserPreferencesDTO userPreferencesDTO = (UserPreferencesDTO) o;
    return Objects.equals(this.id, userPreferencesDTO.id) &&
        Objects.equals(this.preferredLanguage, userPreferencesDTO.preferredLanguage) &&
        Objects.equals(this.emailNotifications, userPreferencesDTO.emailNotifications) &&
        Objects.equals(this.smsNotifications, userPreferencesDTO.smsNotifications) &&
        Objects.equals(this.pushNotifications, userPreferencesDTO.pushNotifications) &&
        Objects.equals(this.phone, userPreferencesDTO.phone) &&
        Objects.equals(this.email, userPreferencesDTO.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, preferredLanguage, emailNotifications, smsNotifications, pushNotifications, phone, email);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserPreferencesDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    preferredLanguage: ").append(toIndentedString(preferredLanguage)).append("\n");
    sb.append("    emailNotifications: ").append(toIndentedString(emailNotifications)).append("\n");
    sb.append("    smsNotifications: ").append(toIndentedString(smsNotifications)).append("\n");
    sb.append("    pushNotifications: ").append(toIndentedString(pushNotifications)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

